view   systemonly  included   .1.3.6.1.2025

rocommunity public 172.17.0.2/32 -V systemonly
rocommunity public 127.0.0.1 -V systemonly

pass 1.3.6.1.2025.1 /usr/local/bin/snmp/snmp-temperature.sh
pass 1.3.6.1.2025.2 /usr/local/bin/snmp/snmp-cpu-usage.sh
pass 1.3.6.1.2025.3 /usr/local/bin/snmp/random-num.sh
pass 1.3.6.1.2025.4 /usr/local/bin/snmp/snmp-memory-usage.sh
pass 1.3.6.1.2025.5 /usr/local/bin/snmp/snmp-port-status.sh