view   systemonly  included   .1.3.6.1.2025

rocommunity public 172.17.0.2/32 -V systemonly
rocommunity public 127.0.0.1 -V systemonly

pass 1.3.6.1.2025.1 /usr/local/bin/snmp/snmp-temperature.sh
pass 1.3.6.1.2025.2 /usr/local/bin/snmp/snmp-cpu-usage.sh
