###########################################################################
# SECTION: System Information Setup
#

sysLocation    "Serwer w Data Center A"
sysContact     "Admin <admin@example.com>"
sysServices    72

###########################################################################
# SECTION: Agent Operating Mode
#

# Agent jako master agent
master agentx

# Agent nasłuchuje na swoim adresie IP
agentaddress udp:161

###########################################################################
# SECTION: Access Control Setup
#

# Widok ograniczony do podstawowych danych systemowych
view   systemonly  included   .1.3.6.1.2.1.1
view   systemonly  included   .1.3.6.1.2.1.25.1
view   systemonly  included   .1.3.6.1.2025

# SNMPv2c - read-only dla community 'public', dostęp tylko dla serwera i localhosta
rocommunity public 172.17.0.2/32 -V systemonly
rocommunity public 127.0.0.1 -V all

# SNMPv2c - read-write dla community 'private' (opcjonalnie), dostęp tylko dla serwera
rwcommunity private 172.17.0.2/32

# SNMPv3 - użytkownik z autoryzacją i szyfrowaniem (authPrivUser)
# createUser authPrivUser SHA myauthpass AES myprivpass
# rouser authPrivUser authpriv -V systemonly

###########################################################################
# SECTION: Additional Settings
#

pass 1.3.6.1.2025.1 /usr/local/bin/snmp/snmp-temperature.sh
pass 1.3.6.1.2025.2 /usr/local/bin/snmp/snmp-cpu-usage.sh


# Włączenie wszystkich dodatkowych plików konfiguracyjnych
includeDir /etc/snmp/snmpd.conf.d

